<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251212100627 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE exam_task (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(20) NOT NULL, original_number VARCHAR(50) DEFAULT NULL, section VARCHAR(255) NOT NULL, topic TEXT DEFAULT NULL, type VARCHAR(255) NOT NULL, max_points SMALLINT NOT NULL, ai_description TEXT DEFAULT NULL, answer_key JSON DEFAULT NULL, position SMALLINT NOT NULL, exam_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_DF9A5D96578D5E91 ON exam_task (exam_id)');
        $this->addSql('ALTER TABLE exam_task ADD CONSTRAINT FK_DF9A5D96578D5E91 FOREIGN KEY (exam_id) REFERENCES exam (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE exam ADD date DATE DEFAULT NULL');
        $this->addSql('ALTER TABLE exam DROP subject');
        $this->addSql('ALTER TABLE exam DROP created_at');
        $this->addSql('ALTER TABLE exam RENAME COLUMN title TO exam_id');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_38BBA6C6578D5E91 ON exam (exam_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE exam_task DROP CONSTRAINT FK_DF9A5D96578D5E91');
        $this->addSql('DROP TABLE exam_task');
        $this->addSql('DROP INDEX UNIQ_38BBA6C6578D5E91');
        $this->addSql('ALTER TABLE exam ADD subject VARCHAR(100) NOT NULL');
        $this->addSql('ALTER TABLE exam ADD created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL');
        $this->addSql('ALTER TABLE exam DROP date');
        $this->addSql('ALTER TABLE exam RENAME COLUMN exam_id TO title');
    }
}
