<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251229144345 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE asset (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(255) NOT NULL, path VARCHAR(1024) NOT NULL, alt_text VARCHAR(255) DEFAULT NULL, group_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_2AF5A5CFE54D947 ON asset (group_id)');
        $this->addSql('CREATE TABLE task_evaluation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, awarded_points INT NOT NULL, rationale TEXT DEFAULT NULL, flags JSON NOT NULL, grader VARCHAR(255) NOT NULL, grader_version VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, exam_attempt_id INT NOT NULL, task_item_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F30EEDAA399C43E ON task_evaluation (exam_attempt_id)');
        $this->addSql('CREATE INDEX IDX_F30EEDAD8E78B4 ON task_evaluation (task_item_id)');
        $this->addSql('CREATE TABLE task_group (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, number INT NOT NULL, stimulus TEXT DEFAULT NULL, exam_page INT DEFAULT NULL, exam_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_AA645FE5578D5E91 ON task_group (exam_id)');
        $this->addSql('CREATE TABLE task_item (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(255) NOT NULL, type VARCHAR(255) NOT NULL, answer_format VARCHAR(255) NOT NULL, max_points INT NOT NULL, prompt TEXT NOT NULL, options JSON DEFAULT NULL, answer_key JSON NOT NULL, grading_rubric TEXT DEFAULT NULL, tags JSON DEFAULT NULL, group_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6CA8B165FE54D947 ON task_item (group_id)');
        $this->addSql('ALTER TABLE asset ADD CONSTRAINT FK_2AF5A5CFE54D947 FOREIGN KEY (group_id) REFERENCES task_group (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE task_evaluation ADD CONSTRAINT FK_F30EEDAA399C43E FOREIGN KEY (exam_attempt_id) REFERENCES exam_attempt (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE task_evaluation ADD CONSTRAINT FK_F30EEDAD8E78B4 FOREIGN KEY (task_item_id) REFERENCES task_item (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE task_group ADD CONSTRAINT FK_AA645FE5578D5E91 FOREIGN KEY (exam_id) REFERENCES exam (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE task_item ADD CONSTRAINT FK_6CA8B165FE54D947 FOREIGN KEY (group_id) REFERENCES task_group (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE student_answer DROP CONSTRAINT fk_54eb92a58db60186');
        $this->addSql('DROP INDEX idx_54eb92a58db60186');
        $this->addSql('ALTER TABLE exam_task DROP CONSTRAINT fk_df9a5d96578d5e91');
        $this->addSql('DROP TABLE exam_task');
        $this->addSql('DROP INDEX uniq_38bba6c6578d5e91');
        $this->addSql('ALTER TABLE exam ADD year INT NOT NULL');
        $this->addSql('ALTER TABLE exam ADD month INT NOT NULL');
        $this->addSql('ALTER TABLE exam ADD type VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE exam DROP date');
        $this->addSql('ALTER TABLE exam_attempt ADD user_id VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE student_answer ADD payload JSON DEFAULT NULL');
        $this->addSql('ALTER TABLE student_answer DROP answer_content');
        $this->addSql('ALTER TABLE student_answer DROP score');
        $this->addSql('ALTER TABLE student_answer DROP feedback');
        $this->addSql('ALTER TABLE student_answer RENAME COLUMN task_id TO task_item_id');
        $this->addSql('ALTER TABLE student_answer ADD CONSTRAINT FK_54EB92A5D8E78B4 FOREIGN KEY (task_item_id) REFERENCES task_item (id) NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_54EB92A5D8E78B4 ON student_answer (task_item_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE exam_task (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, original_number VARCHAR(50) DEFAULT NULL, topic TEXT DEFAULT NULL, ai_description TEXT DEFAULT NULL, answer_key JSON DEFAULT NULL, code VARCHAR(20) NOT NULL, type VARCHAR(255) NOT NULL, section VARCHAR(255) NOT NULL, "position" SMALLINT NOT NULL, max_points SMALLINT NOT NULL, exam_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_df9a5d96578d5e91 ON exam_task (exam_id)');
        $this->addSql('ALTER TABLE exam_task ADD CONSTRAINT fk_df9a5d96578d5e91 FOREIGN KEY (exam_id) REFERENCES exam (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE asset DROP CONSTRAINT FK_2AF5A5CFE54D947');
        $this->addSql('ALTER TABLE task_evaluation DROP CONSTRAINT FK_F30EEDAA399C43E');
        $this->addSql('ALTER TABLE task_evaluation DROP CONSTRAINT FK_F30EEDAD8E78B4');
        $this->addSql('ALTER TABLE task_group DROP CONSTRAINT FK_AA645FE5578D5E91');
        $this->addSql('ALTER TABLE task_item DROP CONSTRAINT FK_6CA8B165FE54D947');
        $this->addSql('DROP TABLE asset');
        $this->addSql('DROP TABLE task_evaluation');
        $this->addSql('DROP TABLE task_group');
        $this->addSql('DROP TABLE task_item');
        $this->addSql('ALTER TABLE exam ADD date DATE DEFAULT NULL');
        $this->addSql('ALTER TABLE exam DROP year');
        $this->addSql('ALTER TABLE exam DROP month');
        $this->addSql('ALTER TABLE exam DROP type');
        $this->addSql('CREATE UNIQUE INDEX uniq_38bba6c6578d5e91 ON exam (exam_id)');
        $this->addSql('ALTER TABLE exam_attempt DROP user_id');
        $this->addSql('ALTER TABLE student_answer DROP CONSTRAINT FK_54EB92A5D8E78B4');
        $this->addSql('DROP INDEX IDX_54EB92A5D8E78B4');
        $this->addSql('ALTER TABLE student_answer ADD answer_content TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE student_answer ADD score INT DEFAULT NULL');
        $this->addSql('ALTER TABLE student_answer ADD feedback TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE student_answer DROP payload');
        $this->addSql('ALTER TABLE student_answer RENAME COLUMN task_item_id TO task_id');
        $this->addSql('ALTER TABLE student_answer ADD CONSTRAINT fk_54eb92a58db60186 FOREIGN KEY (task_id) REFERENCES exam_task (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX idx_54eb92a58db60186 ON student_answer (task_id)');
    }
}
