<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260104154111 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE asset (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(255) NOT NULL, path VARCHAR(1024) NOT NULL, alt_text VARCHAR(255) DEFAULT NULL, group_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_2AF5A5CFE54D947 ON asset (group_id)');
        $this->addSql('CREATE TABLE exam (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, exam_id VARCHAR(255) NOT NULL, year INT NOT NULL, month INT NOT NULL, type VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE exam_attempt (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, status VARCHAR(255) NOT NULL, started_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, submitted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, checked_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, user_id VARCHAR(255) DEFAULT NULL, exam_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_154A5B0E578D5E91 ON exam_attempt (exam_id)');
        $this->addSql('CREATE TABLE student_answer (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, payload JSON DEFAULT NULL, exam_attempt_id INT NOT NULL, task_item_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_54EB92A5A399C43E ON student_answer (exam_attempt_id)');
        $this->addSql('CREATE INDEX IDX_54EB92A5D8E78B4 ON student_answer (task_item_id)');
        $this->addSql('CREATE TABLE task_evaluation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, awarded_points INT NOT NULL, rationale TEXT DEFAULT NULL, flags JSON NOT NULL, grader VARCHAR(255) NOT NULL, grader_version VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, exam_attempt_id INT NOT NULL, task_item_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F30EEDAA399C43E ON task_evaluation (exam_attempt_id)');
        $this->addSql('CREATE INDEX IDX_F30EEDAD8E78B4 ON task_evaluation (task_item_id)');
        $this->addSql('CREATE TABLE task_group (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, number INT NOT NULL, stimulus TEXT DEFAULT NULL, exam_page INT DEFAULT NULL, exam_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_AA645FE5578D5E91 ON task_group (exam_id)');
        $this->addSql('CREATE TABLE task_item (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(255) NOT NULL, type VARCHAR(255) NOT NULL, answer_format VARCHAR(255) NOT NULL, max_points INT NOT NULL, prompt TEXT NOT NULL, options JSON DEFAULT NULL, answer_key JSON NOT NULL, grading_rubric TEXT DEFAULT NULL, tags JSON DEFAULT NULL, group_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6CA8B165FE54D947 ON task_item (group_id)');
        $this->addSql('ALTER TABLE asset ADD CONSTRAINT FK_2AF5A5CFE54D947 FOREIGN KEY (group_id) REFERENCES task_group (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE exam_attempt ADD CONSTRAINT FK_154A5B0E578D5E91 FOREIGN KEY (exam_id) REFERENCES exam (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE student_answer ADD CONSTRAINT FK_54EB92A5A399C43E FOREIGN KEY (exam_attempt_id) REFERENCES exam_attempt (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE student_answer ADD CONSTRAINT FK_54EB92A5D8E78B4 FOREIGN KEY (task_item_id) REFERENCES task_item (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE task_evaluation ADD CONSTRAINT FK_F30EEDAA399C43E FOREIGN KEY (exam_attempt_id) REFERENCES exam_attempt (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE task_evaluation ADD CONSTRAINT FK_F30EEDAD8E78B4 FOREIGN KEY (task_item_id) REFERENCES task_item (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE task_group ADD CONSTRAINT FK_AA645FE5578D5E91 FOREIGN KEY (exam_id) REFERENCES exam (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE task_item ADD CONSTRAINT FK_6CA8B165FE54D947 FOREIGN KEY (group_id) REFERENCES task_group (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE asset DROP CONSTRAINT FK_2AF5A5CFE54D947');
        $this->addSql('ALTER TABLE exam_attempt DROP CONSTRAINT FK_154A5B0E578D5E91');
        $this->addSql('ALTER TABLE student_answer DROP CONSTRAINT FK_54EB92A5A399C43E');
        $this->addSql('ALTER TABLE student_answer DROP CONSTRAINT FK_54EB92A5D8E78B4');
        $this->addSql('ALTER TABLE task_evaluation DROP CONSTRAINT FK_F30EEDAA399C43E');
        $this->addSql('ALTER TABLE task_evaluation DROP CONSTRAINT FK_F30EEDAD8E78B4');
        $this->addSql('ALTER TABLE task_group DROP CONSTRAINT FK_AA645FE5578D5E91');
        $this->addSql('ALTER TABLE task_item DROP CONSTRAINT FK_6CA8B165FE54D947');
        $this->addSql('DROP TABLE asset');
        $this->addSql('DROP TABLE exam');
        $this->addSql('DROP TABLE exam_attempt');
        $this->addSql('DROP TABLE student_answer');
        $this->addSql('DROP TABLE task_evaluation');
        $this->addSql('DROP TABLE task_group');
        $this->addSql('DROP TABLE task_item');
    }
}
