<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251212121144 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE exam_attempt (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, status VARCHAR(255) NOT NULL, started_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, submitted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, checked_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, exam_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_154A5B0E578D5E91 ON exam_attempt (exam_id)');
        $this->addSql('CREATE TABLE student_answer (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, answer_content TEXT DEFAULT NULL, score INT DEFAULT NULL, feedback TEXT DEFAULT NULL, exam_attempt_id INT NOT NULL, task_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_54EB92A5A399C43E ON student_answer (exam_attempt_id)');
        $this->addSql('CREATE INDEX IDX_54EB92A58DB60186 ON student_answer (task_id)');
        $this->addSql('ALTER TABLE exam_attempt ADD CONSTRAINT FK_154A5B0E578D5E91 FOREIGN KEY (exam_id) REFERENCES exam (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE student_answer ADD CONSTRAINT FK_54EB92A5A399C43E FOREIGN KEY (exam_attempt_id) REFERENCES exam_attempt (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE student_answer ADD CONSTRAINT FK_54EB92A58DB60186 FOREIGN KEY (task_id) REFERENCES exam_task (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE exam_attempt DROP CONSTRAINT FK_154A5B0E578D5E91');
        $this->addSql('ALTER TABLE student_answer DROP CONSTRAINT FK_54EB92A5A399C43E');
        $this->addSql('ALTER TABLE student_answer DROP CONSTRAINT FK_54EB92A58DB60186');
        $this->addSql('DROP TABLE exam_attempt');
        $this->addSql('DROP TABLE student_answer');
    }
}
